title:                Rokma Art Photography
short_title:          Rokma
subtitle:             ""
description:          "Rokma art photography is an uplifting, intimate meme play that evocates beauty through light and form. Sometimes abstract, absolutely non personal, mostly non descriptive. Rokma's images are permeated by a charming and unique recognisable style which took his photography artworks to international recognition."
keywords:             art photography, images for interior design, black and white, fine art, fine art prints, form, light painting, global child, photography master, Italian artist, chiaro scuro.
lang:                 en
version:              0.8.0
baseurl:              ""
url:                  "https://art.rokma.com"
qr: show # 'show' or 'hide' put qr.svg in includes/defs.html call it: icn--qr

company:
  name:               #
  legal_name:         #if overrides 'company.name' in footer
  email:              art@rokma.com
  telephone:
  telephone_whatsapp: #
  fax:                #
  address:
  maplink:            #
  country:            #
  twitter:            #
  facebook_page:      "https://web.facebook.com/rokmaphotography"
  youtube:            #
  instagram:          "https://www.instagram.com/rokmaphotography"
  vimeo:

#SEO https://jekyll.github.io/jekyll-seo-tag/usage/
#
# SEO tag will use the YAML front matter if included in a post, page, or document:
#
# title
# description
# image - (e.g., /assets/page-pic.jpg)
# author - Page-specific author (see below)
# lang - Page-specific language

author:               rokma
twitter:
  username:           rokmatwit
facebook:
  app_id:             #Facebook app ID for Facebook insights
  publisher:          #Facebook page URL or ID of the publishing entity
  admins:             #Facebook user ID for domain insights linked to a personal account
logo:                 /assets/favicons/apple-touch-icon-152x152.png

google:
  analytics:          UA-143051704-1
  verification:       google32e66f1a5601ec40

# Build settings
markdown:             kramdown
plugins:
 - jekyll/tagging
 - jekyll-seo-tag
 - jekyll-sitemap
 - html-proofer

exclude:
  - Gemfile.lock
  - node_modules
  - package-lock.json
  - Gemfile

permalink:            /:title/ # pretty

collections:
 series:
  output:             true
  permalink:          /:title/
 about:
  output:             true
  permalink:          /:title/
 pages:
  output:             true
  permalink:          /:title/

defaults:
  - scope:
      type:           posts
    values:
      layout:         "photograph"

tag_page_layout:      post_index_tag
tag_page_dir:         ./
tag_permalink_style:  pretty
ignored_tags:
